const appConfig: any = {
    author: "Gusti Bagus Suandana",
    logo: {
        image: "/logo.png",
        text: "NBK Chord",
        isHomeLink: true,
    },

    title: "NBK Chord",
    description: "Apliaksi chord untuk Nyanyian Bala Keselamatan",
    theme: "light",
    githubRepo: "https://github.com/bagussuandana/nbk-chord",
    routes: [
        {
            name: "Beranda",
            value: "/",
        },
        {
            name: "Daftar Lagu",
            value: "/song-list",
        },
        {
            name: "Kebijakan Privasi",
            value: "/privacy-policy",
        },
        {
            name: "Syarat & Ketentuan",
            value: "/terms-and-conditions",
        },
    ],
    socials: {
        email: "musik.k2dps@gmail.com",
        github: "https://github.com/bagussuandana/nbk-chord",
        twitter: "",
        linkedin: "",
        facebook: "",
        instagram: "",
        youtube: "",
    },
    home: {
        title: "Selamat Datang di NBK Chord",
        description:
            "Apliaksi chord untuk Nyanyian Bala Keselamatan dipersembahkan untuk kemuliaan Tuhan Yesus Kristus",
        hero: {
            image: "/assets/marketing1.svg",
            imageAlt: "/assets/white-wave.svg",
        },
    },
    song_list: {
        title: "Daftar Lagu",
        description:
            "Daftar lagu lagu dari buku lagu Bala Keselamatan dengan mudah, dan nikmati fitur transpose akor untuk memainkan lagu sesuai dengan nada favorit Anda.",
    },
    privacy_policy: {
        title: "Kebijakan Privasi",
        description:
            "Kebijakan privasi ini menjami untuk mengumpulkan, menyimpan, dan memproses data pengguna dalam bentuk apapun. Aplikasi ini sepenuhnya berbasis klien, sehingga data Anda tetap aman dan privat.",
    },
    terms_and_conditions: {
        title: "Syarat dan Ketentuan",
        description:
            "Selamat datang di NBK Chord! Dengan menggunakan aplikasi ini, Anda setuju dengan syarat dan ketentuan berikut:",
    },

    tempos: [
        {
            id: "adagietto",
            name: "adagietto",
            description: "agak lambat, sedikit lebih cepat dari adagio",
            bpm_range: "72-76",
        },
        {
            id: "adagio",
            name: "adagio",
            description: "lambat",
            bpm_range: "66-76",
        },
        {
            id: "allegretto",
            name: "allegretto",
            description: "cukup cepat, sedikit lebih lambat dari allegro",
            bpm_range: "112-120",
        },
        {
            id: "allegrissimo",
            name: "allegrissimo",
            description: "sangat cepat, lebih cepat dari allegro",
            bpm_range: "172-176",
        },
        {
            id: "allegro",
            name: "allegro",
            description: "cepat",
            bpm_range: "120-168",
        },
        {
            id: "allegro-moderato",
            name: "allegro moderato",
            description: "cukup cepat, sedikit lebih lambat dari allegro",
            bpm_range: "116-120",
        },
        {
            id: "andante",
            name: "andante",
            description: "kecepatan berjalan",
            bpm_range: "76-108",
        },
        {
            id: "andante-moderato",
            name: "andante moderato",
            description: "kecepatan berjalan moderat, lebih cepat dari andante",
            bpm_range: "92-112",
        },
        {
            id: "andantino",
            name: "andantino",
            description: "tempo moderat, sedikit lebih cepat dari andante",
            bpm_range: "80-108",
        },
        {
            id: "grave",
            name: "grave",
            description: "sangat lambat",
            bpm_range: "25-45",
        },
        {
            id: "larghetto",
            name: "larghetto",
            description:
                "agak lambat dan lebar, sedikit lebih cepat dari largo",
            bpm_range: "60-66",
        },
        {
            id: "larghissimo",
            name: "larghissimo",
            description: "sangat lambat, lebih lambat dari largo",
            bpm_range: "0-25",
        },
        {
            id: "largo",
            name: "largo",
            description: "sangat lambat dan lebar",
            bpm_range: "40-60",
        },
        {
            id: "lento",
            name: "lento",
            description: "lambat",
            bpm_range: "45-60",
        },
        {
            id: "moderato",
            name: "moderato",
            description: "moderat",
            bpm_range: "108-120",
        },
        {
            id: "prestissimo",
            name: "prestissimo",
            description: "sangat cepat, lebih cepat dari presto",
            bpm_range: "200-999",
        },
        {
            id: "presto",
            name: "presto",
            description: "sangat cepat",
            bpm_range: "168-200",
        },
        {
            id: "vivace",
            name: "vivace",
            description: "cepat dan ringan",
            bpm_range: "140-176",
        },
        {
            id: "vivacissimo",
            name: "vivacissimo",
            description: "sangat cepat dan ringan, lebih cepat dari vivace",
            bpm_range: "172-176",
        },
    ],

    songs: [
        {
            id: "1",
            title: "NBK-1",
            description: "Semua Bagai Misteri",
            chord: "G",
            rhythm: "4/4",
            tempo: "84",
        },
        {
            id: "2",
            title: "NBK-2",
            description: "Besar Setia-Mu",
            chord: "E",
            rhythm: "3/4",
            tempo: "92",
        },
        {
            id: "3",
            title: "NBK-3",
            description: "Betapa Mulia",
            chord: "C",
            rhythm: "4/4",
            tempo: "100",
        },
        {
            id: "4",
            title: "NBK-4",
            description: "Cinta Allah Sungguh Ajaib",
            chord: "G",
            rhythm: "4/4",
            tempo: "144",
        },
        {
            id: "5",
            title: "NBK-5",
            description: "Kau Yang Cinta Tuhan",
            chord: "A#",
            rhythm: "4/4",
            tempo: "120",
        },
        {
            id: "6",
            title: "NBK-6",
            description: "Kalau Kulihat Karya Tuhan",
            chord: "A#",
            rhythm: "4/4",
            tempo: "92",
        },
        {
            id: "7",
            title: "NBK-7",
            description: "Kudus, Kudus Allah yang Kuasa",
            chord: "D#",
            rhythm: "4/4",
            tempo: "92",
        },
        {
            id: "8",
            title: "NBK-8",
            description: "Maha Cinta Tuhan-ku",
            chord: "D#",
            rhythm: "6/8",
            tempo: "112",
        },
        {
            id: "9",
            title: "NBK-9",
            description: "Mari Bersama Menyanyi",
            chord: "D",
            rhythm: "4/4",
            tempo: "112",
        },
        {
            id: "10",
            title: "NBK-10",
            description: "Mari Kita Semua Beri Syukur",
            chord: "F",
            rhythm: "4/4",
            tempo: "96",
        },
        {
            id: "11",
            title: "NBK-11",
            description: "Pujilah Allah",
            chord: "G",
            rhythm: "3/4",
            tempo: "108",
        },
        {
            id: "12",
            title: "NBK-12",
            description: "Pujilah Bersama-Sama",
            chord: "D",
            rhythm: "4/4",
            tempo: "108",
        },
        {
            id: "13",
            title: "NBK-13",
            description: "Pujilah Raja Di Surga",
            chord: "D",
            rhythm: "2/4",
            tempo: "92",
        },
        {
            id: "14",
            title: "NBK-14",
            description: "Raja Kasih Gembalaku",
            chord: "F",
            rhythm: "3/4",
            tempo: "80",
        },
        {
            id: "15",
            title: "NBK-15",
            description: "Raja Yang Mulia",
            chord: "G#",
            rhythm: "3/4",
            tempo: "96",
        },
        {
            id: "16",
            title: "NBK-16",
            description: "S'gala Kemuliaan",
            chord: "G#",
            rhythm: "3/4",
            tempo: "108",
        },
        {
            id: "17",
            title: "NBK-17",
            description: "Sungguh Besar Anugerah",
            chord: "G#",
            rhythm: "3/4",
            tempo: "72",
        },
        {
            id: "18",
            title: "NBK-18",
            description: "Tuhan Itu Gembalaku",
            chord: "A#",
            rhythm: "3/4",
            tempo: "84",
        },
        {
            id: "19",
            title: "NBK-19",
            description: "Tuhan Kekuatanku",
            chord: "D",
            rhythm: "3/4",
            tempo: "104",
        },
        {
            id: "20",
            title: "NBK-20",
            description: "Ada Cerita Yang Baru",
            chord: "G#",
            rhythm: "4/4",
            tempo: "72",
        },
        {
            id: "21",
            title: "NBK-21",
            description: "Baiklah Alam S'kalian",
            chord: "G#",
            rhythm: "4/4",
            tempo: "104",
        },
        {
            id: "22",
            title: "NBK-22",
            description: "Betapa Mulia",
            chord: "G",
            rhythm: "3/4",
            tempo: "120",
        },
        {
            id: "23",
            title: "NBK-23",
            description: "Cinta Ajaib",
            chord: "A#",
            rhythm: "4/4",
            tempo: "72",
        },
        {
            id: "24",
            title: "NBK-24",
            description: "Cinta Sungguh Ajaib",
            chord: "G",
            rhythm: "3/4",
            tempo: "120",
        },
        {
            id: "25",
            title: "NBK-25",
            description: "C'ritakan Pada Saya",
            chord: "C",
            rhythm: "4/4",
            tempo: "120",
        },
        {
            id: "26",
            title: "NBK-26",
            description: "C'rita Yang Amat Indah",
            chord: "D#",
            rhythm: "4/4",
            tempo: "88",
        },
        {
            id: "27",
            title: "NBK-27",
            description: "Imanku Pada Tuhan",
            chord: "C",
            rhythm: "4/4",
            tempo: "120",
        },
        {
            id: "28",
            title: "NBK-28",
            description: "Indah Nama Yesus",
            chord: "F",
            rhythm: "4/4",
            tempo: "120",
        },
        {
            id: "29",
            title: "NBK-29",
            description: "Ingat S'lalu Nama Tuhan",
            chord: "G#",
            rhythm: "4/4",
            tempo: "92",
        },
        {
            id: "30",
            title: "NBK-30",
            description: "Juru S'lamat Ada Dekat",
            chord: "D#",
            rhythm: "6/8",
            tempo: "144",
        },
        {
            id: "31",
            title: "NBK-31",
            description: "Kenalkah Nama Yang Indah",
            chord: "G",
            rhythm: "12/8",
            tempo: "120",
        },
        {
            id: "32",
            title: "NBK-32",
            description: "Ku Tak Mengerti",
            chord: "C#",
            rhythm: "4/4",
            tempo: "60",
        },
        {
            id: "33",
            title: "NBK-33",
            description: "Mari Bersama Memuji",
            chord: "D#",
            rhythm: "4/4",
            tempo: "104",
        },
        {
            id: "34",
            title: "NBK-34",
            description: "Merdu Bunyi Nama Tuhan",
            chord: "C#",
            rhythm: "3/4",
            tempo: "108",
        },
        {
            id: "35",
            title: "NBK-35",
            description: "Nama Yesus",
            chord: "A#",
            rhythm: "3/4",
            tempo: "72",
        },
        {
            id: "36",
            title: "NBK-36",
            description: "O'Yesus Kalau Kukenang",
            chord: "G#",
            rhythm: "3/4",
            tempo: "72",
        },
        {
            id: "37",
            title: "NBK-37",
            description: "Puji Yesus",
            chord: "G#",
            rhythm: "6/8",
            tempo: "192",
        },
        {
            id: "38",
            title: "NBK-38",
            description: "Puji Yesus Juru Penebus",
            chord: "G",
            rhythm: "4/4",
            tempo: "76",
        },
        {
            id: "39",
            title: "NBK-39",
            description: "Terdengar Di Langit",
            chord: "D#",
            rhythm: "4/4",
            tempo: "120",
        },
        {
            id: "40",
            title: "NBK-40",
            description: "Puji Nama Tuhan",
            chord: "G#",
            rhythm: "4/4",
            tempo: "100",
        },
        {
            id: "41",
            title: "NBK-41",
            description: "Tuhan Yesus Pengharapan",
            chord: "D",
            rhythm: "4/4",
            tempo: "120",
        },
        {
            id: "42",
            title: "NBK-42",
            description: "Walau Seribu Lidahku",
            chord: "G",
            rhythm: "4/4",
            tempo: "104",
        },
        {
            id: "43",
            title: "NBK-43",
            description: "Yesus Akan Jadi Raja",
            chord: "F",
            rhythm: "4/4",
            tempo: "104",
        },
        {
            id: "44",
            title: "NBK-44",
            description: "Yesus Nama Yang Termulia",
            chord: "G#",
            rhythm: "3/4",
            tempo: "76",
        },
        {
            id: "45",
            title: "NBK-45",
            description: "Yesus Naik Ke Surga",
            chord: "D",
            rhythm: "4/4",
            tempo: "120",
        },
        {
            id: "46",
            title: "NBK-46",
            description: "Yesus Tuhanku",
            chord: "D#",
            rhythm: "4/4",
            tempo: "56",
        },
        {
            id: "47",
            title: "NBK-47",
            description: "Genaplah Perjanjianmu",
            chord: "C",
            rhythm: "4/4",
            tempo: "104",
        },
        {
            id: "48",
            title: "NBK-48",
            description: "Hembuskanlah Roh-Mu",
            chord: "F",
            rhythm: "3/4",
            tempo: "84",
        },
        {
            id: "49",
            title: "NBK-49",
            description: "Marilah Roh Suci",
            chord: "G#",
            rhythm: "4/4",
            tempo: "104",
        },
        {
            id: "50",
            title: "NBK-50",
            description: "Kristus Api Penyucian",
            chord: "F",
            rhythm: "4/4",
            tempo: "84",
        },
    ],
};

export default appConfig;
