import { Worship } from "@/types/worship";

const worship_1_50: Worship[] = [
    {
        id: "bila-kulihat-bintang-gemerlapan",
        title: "Bila Kulihat Bintang Gemerlapan",
        creator: "GBI PRJ CK7",
        url: "https://www.youtube.com/watch?v=ZHxTCh_CTLg",
        chord: "A",
    },
    {
        id: "gloria",
        title: "Gloria - OFFICIAL MUSIC VIDEO",
        creator: "Symphony Worship Family",
        url: "https://www.youtube.com/watch?v=DQRVlRwWnJ0",
        chord: "D",
    },
    {
        id: "you-are-good",
        title: "You Are Good - Israel Houghton (LIVE RECORDING)",
        creator: "Cornerstone Church",
        url: "https://www.youtube.com/watch?v=708opj5poOc",
        chord: "E",
    },
    {
        id: "tak-terbatas",
        title: "Tak Terbatas | UNDVD Feat. UF Band",
        creator: "UNDVD",
        url: "https://www.youtube.com/watch?v=tIHhhcnkIp4",
        chord: "D",
    },
    {
        id: "doa-yabes",
        title: "Doa Yabes",
        creator: "Impact Music Indonesia",
        url: "https://www.youtube.com/watch?v=JdCKCaKQVSU",
        chord: "F",
    },
    {
        id: "natal-di-hatiku",
        title: "Natal Di Hatiku",
        creator: "UNDVD",
        url: "https://www.youtube.com/watch?v=uZgdUpdv4_0",
        chord: "G",
    },
    {
        id: "dia-lahir-untuk-kami",
        title: "Dia Lahir Untuk Kami",
        creator: "William S. Hays",
        url: "https://www.youtube.com/watch?v=0EDWKZ7ALZQ",
        chord: "C",
    },
    {
        id: "segenap-hidup",
        title: "Segenap Hidup",
        creator: "Symphony Worship Family",
        url: "https://www.youtube.com/watch?v=gIeiXTERRxI",
        chord: "G",
    },
    {
        id: "tetap-setia",
        title: "Tetap Setia",
        creator: "JPCC Worship",
        url: "https://www.youtube.com/watch?v=JDYGY0clMt4",
        chord: "C",
    },
    {
        id: "langit-dan-bumi-pujilah-tuhan",
        title: "Langit dan Bumi Pujilah Tuhan",
        creator: "Symphony Worship Family",
        url: "https://www.youtube.com/watch?v=EqkKt5qUV6U",
        chord: "A",
    },
    {
        id: "ku-ada",
        title: "Maria Shandi - I Am Here",
        creator: "Impact Music Indonesia",
        url: "https://www.youtube.com/watch?v=il2x62nvWWc",
        chord: "C",
    },
    {
        id: "besarkan-nama-tuhan",
        title: "Besarkan Nama Tuhan",
        creator: "Bethany Nginden Surabaya",
        url: "https://www.youtube.com/watch?v=ZzbDCUcZSPw",
        chord: "G",
    },
    {
        id: "penuhkanlah-bejanaku",
        title: "Penuhkanlah Bejanaku",
        creator: "Nanto Hastono",
        url: "https://www.youtube.com/watch?v=WsVESPPYYFk",
        chord: "G",
    },
    {
        id: "kunyanyi-haleluya",
        title: "Kunyanyi Haleluya",
        creator: "Symphony Worship Family",
        url: "https://www.youtube.com/watch?v=uAzf_0RQZtQ",
        chord: "D",
    },
    {
        id: "kemenangan-terjadi-di-sini",
        title: "Kemenangan Terjadi Di Sini",
        creator: "GMS",
        url: "https://www.youtube.com/watch?v=-7sdJ_ZXIsU",
        chord: "G",
    },
    {
        id: "hari-ini-kurasa-bahagia",
        title: "Kasih yang Mempersatukan (Hari Ini Kurasa Bahagia)",
        creator: "GKDI",
        url: "https://www.youtube.com/watch?v=YHcOM7lWYv8",
        chord: "C",
    },
    {
        id: "roh-elkudus-roh-tuhan-holy-spirit-move-again",
        title: "Roh Elkudus Roh Tuhan - Holy Spirit Move Again",
        creator: "BK - Symphony Worship Family",
        url: "https://www.youtube.com/watch?v=_hSvRsd5u3Y",
        chord: "C",
    },
    {
        id: "tahta-sucinya",
        title: "Tahta SuciNya",
        creator: "Gloria Trio",
        url: "https://www.youtube.com/watch?v=-f1_GmVPljw",
        chord: "C",
    },
    {
        id: "hidup-ini-adalah-kesempatan",
        title: "Hidup Ini Adalah Kesempatan",
        creator: "(Cover) | GKDI Worship",
        url: "https://www.youtube.com/watch?v=eXsLLMBclAM",
        chord: "D",
    },
    {
        id: "dia-sungguh-baik-he-is-so-good",
        title: "DIA SUNGGUH BAIK ( HE IS SO GOOD )",
        creator: "Rendy Ekin family",
        url: "https://www.youtube.com/watch?v=OLX75OqazBM",
        chord: "A",
    },
];

export default worship_1_50;
