import { Song } from "@/types/song";

const song_1_50: Song[] = [
    {
        id: "1",
        title: "NBK-1",
        description: "semua bagai misteri",
        chord: "G",
        rhythm: "4/4",
        tempo: "84",
    },
    {
        id: "2",
        title: "NBK-2",
        description: "besar setia-mu",
        chord: "E",
        rhythm: "3/4",
        tempo: "92",
    },
    {
        id: "3",
        title: "NBK-3",
        description: "betapa mulia",
        chord: "C",
        rhythm: "4/4",
        tempo: "100",
    },
    {
        id: "4",
        title: "NBK-4",
        description: "cinta allah sungguh ajaib",
        chord: "G",
        rhythm: "4/4",
        tempo: "144",
    },
    {
        id: "5",
        title: "NBK-5",
        description: "kau yang cinta tuhan",
        chord: "A#",
        rhythm: "4/4",
        tempo: "120",
    },
    {
        id: "6",
        title: "NBK-6",
        description: "kalau kulihat karya tuhan",
        chord: "G",
        rhythm: "4/4",
        tempo: "92",
    },
    {
        id: "7",
        title: "NBK-7",
        description: "kudus, kudus allah yang kuasa",
        chord: "D#",
        rhythm: "4/4",
        tempo: "92",
    },
    {
        id: "8",
        title: "NBK-8",
        description: "maha cinta tuhan-ku",
        chord: "D#",
        rhythm: "6/8",
        tempo: "112",
    },
    {
        id: "9",
        title: "NBK-9",
        description: "mari bersama menyanyi",
        chord: "D",
        rhythm: "4/4",
        tempo: "112",
    },
    {
        id: "10",
        title: "NBK-10",
        description: "mari kita semua berikan syukur",
        chord: "F",
        rhythm: "4/4",
        tempo: "96",
    },
    {
        id: "11",
        title: "NBK-11",
        description: "pujilah allah",
        chord: "G",
        rhythm: "3/4",
        tempo: "108",
    },
    {
        id: "12",
        title: "NBK-12",
        description: "pujilah bersama-sama",
        chord: "E",
        rhythm: "4/4",
        tempo: "108",
    },
    {
        id: "13",
        title: "NBK-13",
        description: "pujilah raja di surga",
        chord: "D",
        rhythm: "2/4",
        tempo: "92",
    },
    {
        id: "14",
        title: "NBK-14",
        description: "raja kasih gembalaku",
        chord: "F",
        rhythm: "3/4",
        tempo: "80",
    },
    {
        id: "15",
        title: "NBK-15",
        description: "raja yang mulia",
        chord: "G#",
        rhythm: "3/4",
        tempo: "96",
    },
    {
        id: "16",
        title: "NBK-16",
        description: "sgala kemuliaan",
        chord: "G#",
        rhythm: "3/4",
        tempo: "108",
    },
    {
        id: "17",
        title: "NBK-17",
        description: "sungguh besar anugerah",
        chord: "G#",
        rhythm: "3/4",
        tempo: "72",
    },
    {
        id: "18",
        title: "NBK-18",
        description: "tuhan itu gembalaku",
        chord: "A#",
        rhythm: "3/4",
        tempo: "84",
    },
    {
        id: "19",
        title: "NBK-19",
        description: "tuhan kekuatanku",
        chord: "D",
        rhythm: "3/4",
        tempo: "104",
    },
    {
        id: "20",
        title: "NBK-20",
        description: "ada cerita yang baru",
        chord: "G#",
        rhythm: "4/4",
        tempo: "72",
    },
    {
        id: "21",
        title: "NBK-21",
        description: "baiklah alam s'kalian",
        chord: "G#",
        rhythm: "4/4",
        tempo: "104",
    },
    {
        id: "22",
        title: "NBK-22",
        description: "betapa mulia",
        chord: "G",
        rhythm: "3/4",
        tempo: "120",
    },
    {
        id: "23",
        title: "NBK-23",
        description: "cinta ajaib",
        chord: "A#",
        rhythm: "4/4",
        tempo: "72",
    },
    {
        id: "24",
        title: "NBK-24",
        description: "cinta sungguh ajaib",
        chord: "G",
        rhythm: "3/4",
        tempo: "120",
    },
    {
        id: "25",
        title: "NBK-25",
        description: "critakan pada saya",
        chord: "C",
        rhythm: "4/4",
        tempo: "120",
    },
    {
        id: "26",
        title: "NBK-26",
        description: "c'rita yang amat indah",
        chord: "D#",
        rhythm: "4/4",
        tempo: "88",
    },
    {
        id: "27",
        title: "NBK-27",
        description: "imanku pada tuhan",
        chord: "C",
        rhythm: "4/4",
        tempo: "120",
    },
    {
        id: "28",
        title: "NBK-28",
        description: "indah nama yesus",
        chord: "F",
        rhythm: "4/4",
        tempo: "120",
    },
    {
        id: "29",
        title: "NBK-29",
        description: "ingat s'lalu nama tuhan",
        chord: "G#",
        rhythm: "4/4",
        tempo: "92",
    },
    {
        id: "30",
        title: "NBK-30",
        description: "juru s'lamat ada dekat",
        chord: "D#",
        rhythm: "6/8",
        tempo: "144",
    },
    {
        id: "31",
        title: "NBK-31",
        description: "kenalkah nama yang indah",
        chord: "G",
        rhythm: "12/8",
        tempo: "120",
    },
    {
        id: "32",
        title: "NBK-32",
        description: "ku tak mengerti",
        chord: "C",
        rhythm: "4/4",
        tempo: "60",
    },
    {
        id: "33",
        title: "NBK-33",
        description: "mari bersama memuji",
        chord: "D#",
        rhythm: "4/4",
        tempo: "104",
    },
    {
        id: "34",
        title: "NBK-34",
        description: "merdu bunyi nama tuhan",
        chord: "C#",
        rhythm: "3/4",
        tempo: "108",
    },
    {
        id: "35",
        title: "NBK-35",
        description: "nama yesus",
        chord: "A#",
        rhythm: "3/4",
        tempo: "72",
    },
    {
        id: "36",
        title: "NBK-36",
        description: "o'yesus kukenang",
        chord: "G#",
        rhythm: "3/4",
        tempo: "72",
    },
    {
        id: "37",
        title: "NBK-37",
        description: "puji yesus",
        chord: "G#",
        rhythm: "6/8",
        tempo: "192",
    },
    {
        id: "38",
        title: "NBK-38",
        description: "puji yesus juru penebus",
        chord: "G",
        rhythm: "4/4",
        tempo: "76",
    },
    {
        id: "39",
        title: "NBK-39",
        description: "terdengar di langit",
        chord: "D#",
        rhythm: "4/4",
        tempo: "120",
    },
    {
        id: "40",
        title: "NBK-40",
        description: "puji nama tuhan",
        chord: "G#",
        rhythm: "4/4",
        tempo: "100",
    },
    {
        id: "41",
        title: "NBK-41",
        description: "tuhan yesus pengharapan",
        chord: "D",
        rhythm: "4/4",
        tempo: "120",
    },
    {
        id: "42",
        title: "NBK-42",
        description: "walau seribu lidahku",
        chord: "G",
        rhythm: "4/4",
        tempo: "104",
    },
    {
        id: "43",
        title: "NBK-43",
        description: "yesus akan jadi raja",
        chord: "F",
        rhythm: "4/4",
        tempo: "104",
    },
    {
        id: "44",
        title: "NBK-44",
        description: "yesus nama yang termulia",
        chord: "G#",
        rhythm: "3/4",
        tempo: "76",
    },
    {
        id: "45",
        title: "NBK-45",
        description: "yesus naik ke surga",
        chord: "D",
        rhythm: "4/4",
        tempo: "120",
    },
    {
        id: "46",
        title: "NBK-46",
        description: "yesus tuhanku",
        chord: "D#",
        rhythm: "4/4",
        tempo: "56",
    },
    {
        id: "47",
        title: "NBK-47",
        description: "genaplah perjanjianmu",
        chord: "C",
        rhythm: "4/4",
        tempo: "104",
    },
    {
        id: "48",
        title: "NBK-48",
        description: "hembuskanlah roh-mu",
        chord: "F",
        rhythm: "3/4",
        tempo: "84",
    },
    {
        id: "49",
        title: "NBK-49",
        description: "marilah roh suci",
        chord: "G#",
        rhythm: "4/4",
        tempo: "104",
    },
    {
        id: "50",
        title: "NBK-50",
        description: "kristus api penyucian",
        chord: "F",
        rhythm: "4/4",
        tempo: "84",
    },
];

export default song_1_50;
