import { Song } from "@/types/song";

const song_101_150: Song[] = [
    {
        id: "101",
        title: "NBK-101",
        description: "akan turut tuhan",
        chord: "G",
        rhythm: "4/4",
        tempo: "76",
    },
    {
        id: "102",
        title: "NBK-102",
        description: "aku dengar berkat",
        chord: "G",
        rhythm: "3/4",
        tempo: "104",
    },
    {
        id: "103",
        title: "NBK-103",
        description: "apa karna saya",
        chord: "G",
        rhythm: "3/4",
        tempo: "96",
    },
    {
        id: "104",
        title: "NBK-104",
        description: "dibawah salib tuhan",
        chord: "G",
        rhythm: "4/4",
        tempo: "72",
    },
    {
        id: "105",
        title: "NBK-105",
        description: "dosa dapat dihapus",
        chord: "G",
        rhythm: "4/4",
        tempo: "100",
    },
    {
        id: "106",
        title: "NBK-106",
        description: "hidup haruslah suci",
        chord: "G",
        rhythm: "4/4",
        tempo: "76",
    },
    {
        id: "107",
        title: "NBK-107",
        description: "jikalau dengan kasih",
        chord: "G",
        rhythm: "4/4",
        tempo: "66",
    },
    {
        id: "108",
        title: "NBK-108",
        description: "padamu batu zaman",
        chord: "C",
        rhythm: "3/4",
        tempo: "96",
    },
    {
        id: "109",
        title: "NBK-109",
        description: "saya dengar cerita",
        chord: "F",
        rhythm: "6/8",
        tempo: "112",
    },
    {
        id: "110",
        title: "NBK-110",
        description: "s'gala keberatanku",
        chord: "G",
        rhythm: "3/4",
        tempo: "69",
    },
    {
        id: "111",
        title: "NBK-111",
        description: "seperti ku ada",
        chord: "F",
        rhythm: "3/4",
        tempo: "76",
    },
    {
        id: "112",
        title: "NBK-112",
        description: "tuhan kusujud",
        chord: "G",
        rhythm: "4/4",
        tempo: "72",
    },
    {
        id: "113",
        title: "NBK-113",
        description: "tuhan yesus ku seru",
        chord: "E",
        rhythm: "6/8",
        tempo: "60",
    },
    {
        id: "114",
        title: "NBK-114",
        description: "tuhan janganlah lalu",
        chord: "G",
        rhythm: "4/4",
        tempo: "76",
    },
    {
        id: "115",
        title: "NBK-115",
        description: "yesus memanggilmu",
        chord: "C",
        rhythm: "6/8",
        tempo: "120",
    },
    {
        id: "116",
        title: "NBK-116",
        description: "allah bri anaknya",
        chord: "A",
        rhythm: "4/4",
        tempo: "120",
    },
    {
        id: "117",
        title: "NBK-117",
        description: "allah milikku",
        chord: "G",
        rhythm: "3/4",
        tempo: "96",
    },
    {
        id: "118",
        title: "NBK-118",
        description: "bersatu dengan tuhan",
        chord: "E",
        rhythm: "4/4",
        tempo: "100",
    },
    {
        id: "119",
        title: "NBK-119",
        description: "berulang ulang",
        chord: "C",
        rhythm: "6/8",
        tempo: "120",
    },
    {
        id: "120",
        title: "NBK-120",
        description: "beserta yesus",
        chord: "A",
        rhythm: "4/4",
        tempo: "90",
    },
    {
        id: "122",
        title: "NBK-122",
        description: "bila menempuh g'lombang kehidupan",
        chord: "D",
        rhythm: "2/4",
        tempo: "84",
    },
];

export default song_101_150;
