import { Song } from "@/types/song";

const song_401_422: Song[] = [
  {
    id: "400",
    title: "NBK-400",
    description: "puji allah",
    chord: "D",
    rhythm: "4/4",
    tempo: "112",
  },
  {
    id: "401",
    title: "NBK-401",
    description: "waktu itu kota daud",
    chord: "G",
    rhythm: "4/4",
    tempo: "76",
  },
  {
    id: "402",
    title: "NBK-402",
    description: "waktu malam sunyi",
    chord: "D",
    rhythm: "3/4",
    tempo: "108",
  },
  {
    id: "403",
    title: "NBK-403",
    description: "yesus tuhan ku datang",
    chord: "C",
    rhythm: "6/8",
    tempo: "120",
  },
  {
    id: "404",
    title: "NBK-404",
    description: "tuhan di tangan-mu",
    chord: "G",
    rhythm: "4/4",
    tempo: "112",
  },
  {
    id: "405",
    title: "NBK-405",
    description: "ada satu yang rela",
    chord: "D",
    rhythm: "4/4",
    tempo: "84",
  },
  {
    id: "406",
    title: "NBK-406",
    description: "apa benar darah tuhan",
    chord: "F",
    rhythm: "3/4",
    tempo: "72",
  },
  {
    id: "407",
    title: "NBK-407",
    description: "atas bukit yang jauh",
    chord: "A",
    rhythm: "6/8",
    tempo: "96",
  },
  {
    id: "408",
    title: "NBK-408",
    description: "bangkitlah jiwaku",
    chord: "D",
    rhythm: "4/4",
    tempo: "104",
  },
  {
    id: "409",
    title: "NBK-409",
    description: "darah yesus berkuasa",
    chord: "E",
    rhythm: "4/4",
    tempo: "112",
  },
  {
    id: "410",
    title: "NBK-410",
    description: "dekat salib golgota",
    chord: "G",
    rhythm: "6/8",
    tempo: "104",
  },
  {
    id: "411",
    title: "NBK-411",
    description: "di bawah salib yesus",
    chord: "E",
    rhythm: "4/4",
    tempo: "84",
  },
  {
    id: "412",
    title: "NBK-412",
    description: "jauh disana ada bukit",
    chord: "A#",
    rhythm: "3/4",
    tempo: "90",
  },
  {
    id: "413",
    title: "NBK-413",
    description: "lihatlah anak domba",
    chord: "F",
    rhythm: "9/8",
    tempo: "84",
  },
  {
    id: "414",
    title: "NBK-414",
    description: "tuhan dengar seruanku",
    chord: "G",
    rhythm: "4/4",
    tempo: "94",
  },
  {
    id: "415",
    title: "NBK-415",
    description: "siapa yang turun",
    chord: "G",
    rhythm: "6/8",
    tempo: "104",
  },
  {
    id: "416",
    title: "NBK-416",
    description: "waktu di padang",
    chord: "G",
    rhythm: "4/4",
    tempo: "92",
  },
  {
    id: "417",
    title: "NBK-417",
    description: "yesus mati di salib",
    chord: "A",
    rhythm: "4/4",
    tempo: "76",
  },
  {
    id: "418",
    title: "NBK-418",
    description: "yesus penuh derita",
    chord: "A#",
    rhythm: "4/4",
    tempo: "112",
  },
  {
    id: "419",
    title: "NBK-419",
    description: "di dalam kubur gelap",
    chord: "C",
    rhythm: "4/4",
    tempo: "84",
  },
  {
    id: "420",
    title: "NBK-420",
    description: "kuturut juru selamat",
    chord: "A#",
    rhythm: "6/8",
    tempo: "108",
  },
  {
    id: "421",
    title: "NBK-421",
    description: "maria jalan ke surga",
    chord: "E",
    rhythm: "3/4",
    tempo: "90",
  },
  {
    id: "422",
    title: "NBK-422",
    description: "o,kesukaan yang baka",
    chord: "C",
    rhythm: "4/4",
    tempo: "104",
  },
  {
    id: "423",
    title: "NBK-423",
    description: "suara sorak terdengar",
    chord: "C",
    rhythm: "4/8",
    tempo: "90",
  },
  {
    id: "424",
    title: "NBK-424",
    description: "yesus sudah bangkit",
    chord: "C",
    rhythm: "4/4",
    tempo: "92",
  },
  {
    id: "425",
    title: "NBK-425",
    description: "yesus tuhan bangkit",
    chord: "C",
    rhythm: "4/4",
    tempo: "84",
  },
  {
    id: "426",
    title: "NBK-426",
    description: "apa yang patut ku brikan",
    chord: "G",
    rhythm: "4/4",
    tempo: "90",
  },
  {
    id: "427",
    title: "NBK-427",
    description: "bawalah persembahan",
    chord: "A#",
    rhythm: "3/4",
    tempo: "72",
  },
  {
    id: "428",
    title: "NBK-428",
    description: "nyanyilah bagi tuhan",
    chord: "E",
    rhythm: "3/4",
    tempo: "90",
  },
  {
    id: "429",
    title: "NBK-429",
    description: "spanjang musim",
    chord: "E",
    rhythm: "3/4",
    tempo: "90",
  },
  {
    id: "430",
    title: "NBK-430",
    description: "tabur benih",
    chord: "C",
    rhythm: "6/8",
    tempo: "108",
  },
  {
    id: "431",
    title: "NBK-431",
    description: "tanam waktu pagi",
    chord: "C",
    rhythm: "4/4",
    tempo: "108",
  },
  {
    id: "432",
    title: "NBK-432",
    description: "tuhan berkati kini",
    chord: "A",
    rhythm: "3/4",
    tempo: "96",
  },
  {
    id: "433",
    title: "NBK-433",
    description: "tuhan biar kasihmu",
    chord: "G",
    rhythm: "3/4",
    tempo: "90",
  },
  {
    id: "434",
    title: "NBK-434",
    description: "allah penolongku dulu",
    chord: "A#",
    rhythm: "4/4",
    tempo: "84",
  },
  {
    id: "435",
    title: "NBK-435",
    description: "trima kasih untuk smua",
    chord: "A",
    rhythm: "3/4",
    tempo: "84",
  },
  {
    id: "436",
    title: "NBK-436",
    description: "untuk s'mua kemenangan",
    chord: "A",
    rhythm: "3/4",
    tempo: "90",
  },
  {
    id: "437",
    title: "NBK-437",
    description: "tidak ada sesuatu",
    chord: "G",
    rhythm: "3/4",
    tempo: "84",
  },
  {
    id: "438",
    title: "NBK-438",
    description: "tuhan besertamu",
    chord: "C",
    rhythm: "4/4",
    tempo: "90",
  },
  {
    id: "439",
    title: "NBK-439",
    description: "tuhan berkati",
    chord: "A#",
    rhythm: "4/4",
    tempo: "60",
  },
  {
    id: "440",
    title: "NBK-440",
    description: "b'rilah berkatmu",
    chord: "A",
    rhythm: "4/4",
    tempo: "66",
  },
  {
    id: "441",
    title: "NBK-441",
    description: "moga rahmat yesus",
    chord: "C",
    rhythm: "3/4",
    tempo: "90",
  },
  {
    id: "442",
    title: "NBK-442",
    description: "moga rahmat kristus",
    chord: "D",
    rhythm: "4/4",
    tempo: "112",
  },
];

export default song_401_422;
