import { Song } from "@/types/song";

const song_50_100: Song[] = [
  {
    id: "51",
    title: "NBK-51",
    description: "permintaan doa kami",
    chord: "D#",
    rhythm: "4/4",
    tempo: "92",
  },
  {
    id: "52",
    title: "NBK-52",
    description: "roh kasih yang abadi",
    chord: "D#",
    rhythm: "4/4",
    tempo: "88",
  },
  {
    id: "53",
    title: "NBK-53",
    description: "roh yang suci",
    chord: "D",
    rhythm: "3/4",
    tempo: "84",
  },
  {
    id: "54",
    title: "NBK-54",
    description: "roh el kudus roh tuhan",
    chord: "D",
    rhythm: "3/4",
    tempo: "72",
  },
  {
    id: "55",
    title: "NBK-55",
    description: "roh yang rihman",
    chord: "G",
    rhythm: "3/4",
    tempo: "96",
  },
  {
    id: "56",
    title: "NBK-56",
    description: "turunlah seperti dahulu",
    chord: "G",
    rhythm: "4/4",
    tempo: "72",
  },
  {
    id: "57",
    title: "NBK-57",
    description: "tuhan yesus kami datang",
    chord: "G",
    rhythm: "9/8",
    tempo: "144",
  },
  {
    id: "58",
    title: "NBK-58",
    description: "ada neg'ri jauh",
    chord: "D#",
    rhythm: "4/4",
    tempo: "112",
  },
  {
    id: "59",
    title: "NBK-59",
    description: "ada satu neg'ri senang",
    chord: "D",
    rhythm: "6/8",
    tempo: "120",
  },
  {
    id: "60",
    title: "NBK-60",
    description: "apa ada harapan",
    chord: "C",
    rhythm: "4/4",
    tempo: "104",
  },
  {
    id: "61",
    title: "NBK-61",
    description: "apa cinta tuhan itu",
    chord: "A",
    rhythm: "4/4",
    tempo: "66",
  },
  {
    id: "62",
    title: "NBK-62",
    description: "apa kau ada tempat",
    chord: "A",
    rhythm: "4/4",
    tempo: "84",
  },
  {
    id: "63",
    title: "NBK-63",
    description: "apa yang sedang kau cari",
    chord: "G",
    rhythm: "3/4",
    tempo: "96",
  },
  {
    id: "64",
    title: "NBK-64",
    description: "apa hatimu berduka",
    chord: "G",
    rhythm: "3/4",
    tempo: "96",
  },
  {
    id: "65",
    title: "NBK-65",
    description: "apa kau rasa letih?",
    chord: "G#",
    rhythm: "3/4",
    tempo: "108",
  },
  {
    id: "66",
    title: "NBK-66",
    description: "belum kau dengar",
    chord: "G#",
    rhythm: "3/4",
    tempo: "120",
  },
  {
    id: "67",
    title: "NBK-67",
    description: "berjuta-juta jiwa",
    chord: "A#",
    rhythm: "4/4",
    tempo: "104",
  },
  {
    id: "68",
    title: "NBK-68",
    description: "berkat damai",
    chord: "D",
    rhythm: "4/4",
    tempo: "76",
  },
  {
    id: "69",
    title: "NBK-69",
    description: "betapa besar",
    chord: "G",
    rhythm: "3/4",
    tempo: "n/a",
  },
  {
    id: "70",
    title: "NBK-70",
    description: "datanglah orang berdosa",
    chord: "G",
    rhythm: "4/4",
    tempo: "112",
  },
  {
    id: "71",
    title: "NBK-71",
    description: "dengan kasih sayang",
    chord: "G#",
    rhythm: "6/8",
    tempo: "112",
  },
  {
    id: "72",
    title: "NBK-72",
    description: "dengarlah injil",
    chord: "D#",
    rhythm: "4/4",
    tempo: "84",
  },
  {
    id: "73",
    title: "NBK-73",
    description: "dengarlah suara tuhan",
    chord: "G",
    rhythm: "3/2",
    tempo: "144",
  },
  {
    id: "74",
    title: "NBK-74",
    description: "dengarlah yesus",
    chord: "G#",
    rhythm: "3/4",
    tempo: "120",
  },
  {
    id: "75",
    title: "NBK-75",
    description: "diseluruh pelosok",
    chord: "C",
    rhythm: "4/4",
    tempo: "90",
  },
  {
    id: "76",
    title: "NBK-76",
    description: "dosa merah kirmizi",
    chord: "A#",
    rhythm: "3/4",
    tempo: "72",
  },
  {
    id: "77",
    title: "NBK-77",
    description: "gugur bunga yang indah",
    chord: "D#",
    rhythm: "4/4",
    tempo: "88",
  },
  {
    id: "78",
    title: "NBK-78",
    description: "hanya selangkah saja",
    chord: "G#",
    rhythm: "6/8",
    tempo: "88",
  },
  {
    id: "79",
    title: "NBK-79",
    description: "jangan dukakan roh suci",
    chord: "D#",
    rhythm: "3/4",
    tempo: "92",
  },
  {
    id: "80",
    title: "NBK-80",
    description: "k’lak jumpa yesus",
    chord: "D#",
    rhythm: "4/4",
    tempo: "144",
  },
  {
    id: "81",
    title: "NBK-81",
    description: "kubawa kabar",
    chord: "G",
    rhythm: "4/4",
    tempo: "108",
  },
  {
    id: "82",
    title: "NBK-82",
    description: "lihatlah aku mengetuk",
    chord: "G#",
    rhythm: "4/4",
    tempo: "72",
  },
  {
    id: "83",
    title: "NBK-83",
    description: "malam g'lap t'lah tiba",
    chord: "F",
    rhythm: "4/4",
    tempo: "60",
  },
  {
    id: "84",
    title: "NBK-84",
    description: "mari kepada juru selamat",
    chord: "A#",
    rhythm: "4/4",
    tempo: "96",
  },
  {
    id: "85",
    title: "NBK-85",
    description: "mari orang berdosa",
    chord: "D",
    rhythm: "3/4",
    tempo: "104",
  },
  {
    id: "86",
    title: "NBK-86",
    description: "maukah kau bebas?",
    chord: "G#",
    rhythm: "4/4",
    tempo: "96",
  },
  {
    id: "87",
    title: "NBK-87",
    description: "nyanyikan padaku s'lalu",
    chord: "G",
    rhythm: "6/8",
    tempo: "122",
  },
  {
    id: "88",
    title: "NBK-88",
    description: "orang berdosa dengar",
    chord: "D#",
    rhythm: "4/4",
    tempo: "108",
  },
  {
    id: "89",
    title: "NBK-89",
    description: "orang jauh dari allah",
    chord: "G",
    rhythm: "4/4",
    tempo: "56",
  },
  {
    id: "90",
    title: "NBK-90",
    description: "para perintis",
    chord: "D#",
    rhythm: "4/4",
    tempo: "84",
  },
  {
    id: "91",
    title: "NBK-91",
    description: "pancaran darah kudus",
    chord: "D#",
    rhythm: "3/4",
    tempo: "96",
  },
  {
    id: "92",
    title: "NBK-92",
    description: "pulang, domba penat",
    chord: "F",
    rhythm: "6/8",
    tempo: "100",
  },
  {
    id: "93",
    title: "NBK-93",
    description: "siapakah mengikut yesus",
    chord: "A#",
    rhythm: "4/4",
    tempo: "104",
  },
  {
    id: "94",
    title: "NBK-94",
    description: "siapapun mendengar",
    chord: "D",
    rhythm: "4/4",
    tempo: "104",
  },
  {
    id: "95",
    title: "NBK-95",
    description: "sudah menerima undangan",
    chord: "G#",
    rhythm: "4/4",
    tempo: "92",
  },
  {
    id: "96",
    title: "NBK-96",
    description: "sungguh ajaib kasih tuhan",
    chord: "F",
    rhythm: "4/4",
    tempo: "76",
  },
  {
    id: "97",
    title: "NBK-97",
    description: "sungguh engkau penat",
    chord: "E",
    rhythm: "4/4",
    tempo: "88",
  },
  {
    id: "98",
    title: "NBK-98",
    description: "tempat perlindungan",
    chord: "C",
    rhythm: "3/4",
    tempo: "66",
  },
  {
    id: "99",
    title: "NBK-99",
    description: "yang berdosa penat",
    chord: "G#",
    rhythm: "3/4",
    tempo: "104",
  },
  {
    id: "100",
    title: "NBK-100",
    description: "adakah tersedia",
    chord: "C",
    rhythm: "3/4",
    tempo: "84",
  },
];

export default song_50_100;
